services:
  discovery-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8761:8761"
    networks:
      - mini-project-net

networks:
  mini-project-net:
    external: true